### ISSUE TITLE
Proposal/Request: Decouple coat roughness from transmission/refraction

### ISSUE THREAD

**Issue by sharktacos** [AcademySoftwareFoundation/OpenPBR#197]
Is there a means to decouple specular roughness from affecting transmission/refraction? In the Standard Surface, this could be accomplished with coat roughness which did not affect the transmission roughness. In Open PBR the coat roughness appears to affect the transmission, as does the specular roughness. I would wish that the coat did not affect the transmission so for example one could create scratches on a transparent surface without making the underlying substrate into (expensive to render) frosted glass.

**Comment by portsmouth** [comment]
Do you mean that for example you want a thin pane of glass, which appears rough/frosted viewed from one side, but clear/smooth on the other side?

That's a bit problematic for OpenPBR since it would be explicitly unphysical (at least, I can't think of any physical way of achieving that). But even with OpenPBR it could be done I assume with some shader hacks, i.e. making the roughness depend on the view direction, which I think might be a better approach than baking such a non-physical effect into the model.

**Comment by portsmouth** [comment]
If you model the grime as the fuzz layer, then it would behave something like what you describe, as currently we assume the fuzz does not roughen the transmission. I think that could make sense physically, since e.g. if the fuzz is just absorbing the incident light without scattering, it would not affect the transmission roughness.

For the coat, we do assume it explicitly roughens the transmission (if the coat is rough), since physically it must as the rough microfacet surface will roughen both the reflection and transmission.  In the case of a real pane of glass, I think it must be the case also that if it is scratched up to the point that it looks frosted from the outside, the transmission (seen from the inside) must appear frosted too. So if one wants to avoid that, some hack is needed like just turning off the roughness if the camera is inside.

**Comment by sharktacos** [comment]
Ah yes, that makes sense. Thanks very much for explaining that workflow. Always good for us artists to learn how to do things in a physically correct way, especially with a shader with PBR in its name!
