### ISSUE TITLE
specular_ior_level parameter discussion

### ISSUE THREAD

**Issue by portsmouth** [AcademySoftwareFoundation/OpenPBR#64]
@brechtvl wrote:

How to both have a specular IOR that takes values outside the 0..1 range and still allow texturing is something we struggled with as well. specular_ior_level is an interesting solution. I find the term "level" a bit unclear, I'd maybe call it specular_ior_texture to clarify its purpose, though that could be confusing in other ways.

**Comment by AlexTessier11** [comment]
I was kind of surprised by this parameter. It seems to me it is quite redundant with the spec_ior parameter. It effectively does the same thing, if you start with the idea that textures are a compilation of multiple materials layered on top of each other. Different material, different IOR. If you want to create a ior map in the 0-1 range, you can use the formula 1/ior to create your map, and use it again in your DCC to make it IOR values again. There is obviously a little work to be done to add this to your pipeline though, but here how it works:

For example, for a IOR of 1.5, you would put 0.667 in your map(1/1.5). For a IOR of 100, you would put 0.010(1/100). In your DCC, you connect the map to a divide node(1 divided by your map to make it over 1 again) and a clamp node between 0.001 and 1.0(as a protection for artists who would put 0.0 in the IOR map). 

We've been using this for a bunch of years and it works great. 

As for the specular_weight acting like the specular_ior_level, I think it is a very bad idea, because in production we need an easy way to completely turn off the spec. Turning if off with the spec_color would be the only option left and it feels like using a hammer to drive a screw.

**Comment by portsmouth** [comment]
>As for the specular_weight acting like the specular_ior_level, I think it is a very bad idea, because in production we need an easy way to completely turn off the spec. Turning if off with the spec_color would be the only option left and it feels like using a hammer to drive a screw.

Note that turning the `specular_weight` to 0 *does* completely turn off the spec (since IOR -> 1). If you play around with it in https://portsmouth.github.io/OpenPBR-glsl-example/, you should find it behaves almost exactly the same as the former weight parameter.
