### ISSUE TITLE
Anisotropy parametrisation

### ISSUE THREAD

**Issue by virtualzavie** [AcademySoftwareFoundation/OpenPBR#82]
In the current draft of the spec, a few parametrisations references are mentioned, and we propose a new one.
We are yet to confirm what parametrisation we want to use.

To help evaluate the models, here are some renders.
The roughness goes from 0 on the left to 1 on the right, and the anisotropy goes from 0 at the top, to 1 at the bottom.

## Burley 2012 (Disney model)

$$
\alpha_t = \frac{r^2}{\sqrt{1 - 0.9 a}}, \quad\alpha_b = r^2 \sqrt{1 - 0.9 a}
$$

where $0.9$ is a value chosen to limit the aspect ratio of the specular highlight to $10:1$.

![2023-08-16 anisotropy-mapping-Burley2012](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/9511025/cc0e417b-fa45-4811-b910-b0d13059a63d)

## Georgiev2019 (Standard Surface)

$$
\alpha_t = \mathrm{min}\bigl(\frac{r^2}{\sqrt{1-a}}, 1.0\bigr), \quad\alpha_b = r^2 \sqrt{1-a}
$$

![2023-08-16 anisotropy-mapping-Georgiev2019](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/9511025/ec036673-2d39-4a45-81ad-5bfd293ec452)

## Kulla 2017 (Sony Pictures Imageworks)

$$
\alpha_t = r^2 (1 + a), \quad\alpha_b = r^2 (1 - a)
$$

![2023-08-16 anisotropy-mapping-Kulla2017](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/9511025/64f734a9-a73f-44f1-993f-b2fac6c20fa6)

## Neubelt 2013 (The Order: 1886)

$$
\alpha_t = r^2, \quad\alpha_b = \mathrm{lerp}(0, r^2, 1 - a)
$$

![2023-08-16 anisotropy-mapping-Neubelt2013](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/9511025/1d69a01f-cae2-404d-a30f-62efe440be18)

## Kutz2021 (Adobe Standard Material)

$$
\alpha_t = r^2 + a^4, \quad\alpha_b = r^2
$$

![2023-08-16 anisotropy-mapping-Kutz2021](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/9511025/2e5812ec-0b32-49e5-9c71-d0a964689af1)

## Current OpenPBR proposed mapping

$$
\alpha_t = r^2 \sqrt{\frac{2}{1 + (1 - a)^2}}, \quad\alpha_b = (1 - a) \, \alpha_t
$$

![2023-08-16 anisotropy-mapping-OpenPBR2023](https://github.com/AcademySoftwareFoundation/OpenPBR/assets/9511025/c71b5963-a339-4b77-b7f5-76d1c54a2393)

**Comment by portsmouth** [comment]
@elalish 

We considered that parametrization (i.e. the Adobe one), and overall we thought that it's problematic that the overall roughness should change as the anisotropy changes (diluting the meaning of the roughness parameter, and making it harder to dial in the average roughness first). Also we wanted to keep the effect as linear as possible in the 2d space, which the renders above indicate the OpenPBR mapping does a better job.

This seems a hard one to get universal agreement, since there's an element of arbitrariness and taste. At least, whatever different models choose, you can map between them easily enough.

**Comment by portsmouth** [comment]
Can be closed as we've settled on a parametrization (apart from the flow-map issue of https://github.com/AcademySoftwareFoundation/OpenPBR/issues/155).
